import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

const builtins = [...new Set([...builtinModules, ...builtinModules.map((moduleName) => `node:${moduleName}`)])];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

async function build() {
  const context = await esbuild.context({
    banner: {
      js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    loader: {
      ".md": "text"
    },
    external: [
      "obsidian",
      "electron",
      "plotly.js",
      "date-holidays",
      "@codemirror/autocomplete",
      "@codemirror/closebrackets",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/comment",
      "@codemirror/fold",
      "@codemirror/gutter",
      "@codemirror/highlight",
      "@codemirror/history",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/matchbrackets",
      "@codemirror/panel",
      "@codemirror/rangeset",
      "@codemirror/rectangular-selection",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/stream-parser",
      "@codemirror/text",
      "@codemirror/tooltip",
      "@codemirror/view",
      ...builtins,
    ],
    format: "cjs",
    target: "es2022",
    logLevel: "info",
    minify: prod,
    legalComments: prod ? 'none' : 'eof',
    pure: prod ? ['console.log'] : [],
    drop: prod ? ['debugger'] : [],
    alias: {
      'react': 'preact/compat',
      'react-dom/client': 'preact/compat/client',
      'react-dom': 'preact/compat',
    },
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    entryNames: "[name]", // Use the entry name as the output name
    plugins: [
      {
        name: 'rename-css-plugin',
        setup(build) {
          build.onEnd(() => {

            const rootDir = process.cwd();

            if (prod) {
              try {
                console.log(" | Running Terser minification...");
                execSync('npx -y terser@latest main.js --compress --mangle -o main.js');
                console.log(" | Terser minification completed successfully.");
              } catch (err) {
                console.warn("⚠️ Terser minification failed:", err);
              }
            }
            const devEnvDir = "obsidian-dev-vault/.obsidian/plugins/full-calendar-remastered";
            const oldCssPath = path.join(rootDir, "main.css");
            const newCssPath = path.join(rootDir, "styles.css");

            // Rename CSS file
            if (fs.existsSync(oldCssPath)) {
              fs.renameSync(oldCssPath, newCssPath);
              console.log(" | Renamed CSS to styles.css");
            } else {
              console.warn("⚠️ CSS file not found to rename");
            }

            // Ensure output directory exists
            try {
              if (!fs.existsSync(devEnvDir)) {
                fs.mkdirSync(devEnvDir, { recursive: true });
              }
            } catch (err) {
              console.warn("⚠️ Could not create output directory:", err);
            }

            // Copy main.js and styles.css to dev environment
            try {
              fs.copyFileSync(path.join(rootDir, "main.js"), path.join(devEnvDir, "main.js"));
              if (fs.existsSync(newCssPath)) {
                fs.copyFileSync(newCssPath, path.join(devEnvDir, "styles.css"));
              }
              console.log(" | Copied main.js and styles.css to dev vault");
            } catch (err) {
              console.warn("⚠️ Could not copy build files to dev vault:", err);
            }

            // Copy manifest.json
            const manifestSrc = path.join(rootDir, "manifest-beta.json");
            const manifestDest = path.join(devEnvDir, "manifest.json");
            try {
              fs.copyFileSync(manifestSrc, manifestDest);
              console.log(" | Copied manifest.json to dev vault");
            } catch (err) {
              console.warn("⚠️ Could not copy manifest.json:", err);
            }
          });
        }
      }
    ],
    outfile: "main.js",
    metafile: true,
  });

  if (!prod) {
    context.watch();
    console.log('Watching for changes...');
  } else {
    const result = await context.rebuild();
    fs.writeFileSync("metafile.json", JSON.stringify(result.metafile));
    context.dispose();
  }
}

build().catch(() => process.exit(1));