import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from 'fs';
import path from 'path';

const builtins = [...new Set([...builtinModules, ...builtinModules.map((moduleName) => `node:${moduleName}`)])];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

async function build() {
  const context = await esbuild.context({
    banner: {
      js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "@codemirror/autocomplete",
      "@codemirror/closebrackets",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/comment",
      "@codemirror/fold",
      "@codemirror/gutter",
      "@codemirror/highlight",
      "@codemirror/history",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/matchbrackets",
      "@codemirror/panel",
      "@codemirror/rangeset",
      "@codemirror/rectangular-selection",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/stream-parser",
      "@codemirror/text",
      "@codemirror/tooltip",
      "@codemirror/view",
      ...builtins,
    ],
    format: "cjs",
    target: "es2016",
    logLevel: "info",
    minify: prod,
    legalComments: prod ? 'none' : 'eof',
    // drop: prod ? ['console', 'debugger'] : [],
    alias: {
      'react': 'preact/compat',
      'react-dom/client': 'preact/compat/client',
      'react-dom': 'preact/compat',
    },
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    entryNames: "[name]", // Use the entry name as the output name
    plugins: [
      {
        name: 'rename-css-plugin',
        setup(build) {
          build.onEnd(() => {

            const outputDir = "obsidian-dev-vault/.obsidian/plugins/full-calendar-remastered";
            const oldCssPath = path.join(outputDir, "main.css");
            const newCssPath = path.join(outputDir, "styles.css");

            // Rename CSS file
            if (fs.existsSync(oldCssPath)) {
              fs.renameSync(oldCssPath, newCssPath);
              console.log(" | Renamed CSS to styles.css");
            } else {
              console.warn("⚠️ CSS file not found to rename");
            }

            // Copy manifest.json
            const manifestSrc = path.join(process.cwd(), "manifest-beta.json");
            const manifestDest = path.join(outputDir, "manifest.json");
            try {
              fs.copyFileSync(manifestSrc, manifestDest);
              console.log(" | Copied manifest.json to dev vault");
            } catch (err) {
              console.warn("⚠️ Could not copy manifest.json:", err);
            }
          });
        }
      }
    ],
    outfile: "obsidian-dev-vault/.obsidian/plugins/full-calendar-remastered/main.js",
    metafile: true,
  });

  if (!prod) {
    context.watch();
    console.log('Watching for changes...');
  } else {
    const result = await context.rebuild();
    // fs.writeFileSync("metafile.json", JSON.stringify(result.metafile));
    context.dispose();
  }
}

build().catch(() => process.exit(1));